services:
  dev_api:
    build: ./dev_api
    ports:
      - ${DEV_API_PORT}:${DEV_API_PORT}
    env_file:
      - .env
    depends_on:
      - mongo
  user_api:
    build: ./user_api
    ports:
      - ${USER_API_PORT}:${USER_API_PORT}
    env_file:
      - .env
    depends_on:
      - mongo
  test_api:
    build: ./test_api
    ports:
      - ${TEST_API_PORT}:${TEST_API_PORT}
    env_file:
      - .env
    depends_on:
      - mongo
  mqtt_con:
    build: ./mqtt_con
    env_file:
      - .env
    depends_on:
      - dev_api
  mongo:
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    env_file:
      - .env

